server:
  port: 8084
spring:
  datasource:
    url: jdbc:h2:~/MBA/projects/spring/h2/acquirerdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  batch:
    jdbc:
      initialize-schema: always
      platform: h2
      schema: classpath:schema-h2.sql
fiap:
  acquirer:
    resource: hw-spring-basecliente.csv
